### ISSUE TITLE
compatible with hacs

### ISSUE THREAD

**Issue by marine1988** [Jezza34000/homeassistant_weback_component#1]
can you please change file system to be compatible with hacs?

**Comment by Jezza34000** [comment]
Hi, ok i know what is HACS but i don't understand your request about the file system ?

**Comment by bihlmaier** [comment]
To make this repository/integration work in hacs, you need to store each integration files inside a folder named custom_components/homeassistant_weback_component/ or provice a hacs.json file.

I Created a Pull request for this.
#2

**Comment by Jezza34000** [comment]
Thank you for information @bihlmaier
It's done
