### ISSUE TITLE
Weback issues trying to connect the Vacuum 

### ISSUE THREAD

**Issue by JPNARF** [Jezza34000/homeassistant_weback_component#10]
Hi Jezza34000, 
First of all, excelent job... congratulations.

And the second, is that from December, I can't connect my vacuum to the app. Suddenly stop working, and delete my device then tried to add without lucky. 
I look at the Android Play Store, and there are a lot of people with the same issue.

So, this componet didnt work for me, at the moment becasue can "find" the vacuum because is not added in the weback servers.

Do you have any idea how I can check with is not adding my device anymore? in the Weback severs or wherever is try to add.

Thanks!

**Comment by talss89** [comment]
Hi @JPNARF,

Is this issue related to this Home Assistant component, or the Weback app?

If you haven't already tried the following instructions (API Change 2022), they may help:
https://github.com/Jezza34000/homeassistant_weback_component#important--api-change-since-2022

**Comment by talss89** [comment]
@JPNARF I think this is an issue with your device or Weback app, not this HA component.

It looks like the problem you face is a WiFi / RF issue. Have you made sure your WiFi is running on 2.4Ghz only while trying to add the device?

**Comment by JPNARF** [comment]
> @JPNARF I think this is an issue with your device or Weback app, not this HA component.
> 
> It looks like the problem you face is a WiFi / RF issue. Have you made sure your WiFi is running on 2.4Ghz only while trying to add the device?

Yes, for me the issue is on Weback app.
Since in my router I can see  that an IP has been assigned to that device.

I tried in 3 different WIFI networks, without any lucky.
Always using 2.4GHz only.

This starting happening in December 2022. 
And in the Comments/reviews of the play store looks like all the people facing same issue

https://play.google.com/store/apps/details?id=com.yugong.Backome

Im from Argentina.

**Comment by talss89** [comment]
Ah, that's frustrating!

I'm in the UK - we had Weback cloud problems in December 2022, but it's now working again. I think the Weback cloud isn't properly maintained and is unreliable.

Could you try deleting your account and reregistering in a different region (UK is working for me)?

If that doesn't work, you might have to ask for support from the Weback developer directly: yugong@yg-ai.com

**Comment by JPNARF** [comment]
> > Ah, that's frustrating!
> > I'm in the UK - we had Weback cloud problems in December 2022, but it's now working again. I think the Weback cloud isn't properly maintained and is unreliable.
> > Could you try deleting your account and reregistering in a different region (UK is working for me)?
> > If that doesn't work, you might have to ask for support from the Weback developer directly: [yugong@yg-ai.com](mailto:yugong@yg-ai.com)
> 
> Thanks @talss89 I will try that, and let you know.

Didn't works :(

Maybe is checking My External IP, from Argentina and is not working.

Not checking the account region, but the IP Address of my country.

I will contact the support.
I hope this issue solve quickly so I can check the HA Component.

Thanks!

**Comment by Jezza34000** [comment]
Hi,
I heart about that problem you describe, some people has experienced same issues.
But i don't have any solution for you, you should try to send message to your robot support.
I close this issue that does not concern directly the plugin but WeBack.
I you find any solution, or any information form support don't hesitate to post here maybe that could help some other people :+1:
