### ISSUE TITLE
Not all devices return `hismap_id`

### ISSUE THREAD

**Issue by talss89** [Jezza34000/homeassistant_weback_component#11]
Code from #8 relies on the `hismap_id` property being present in thing status in order to retrieve the correct map.

Not all devices return this property.

- How do we detect the active map on non `hismap_id` devices?
- Is `hismap_id` non-standard?

Raising issue so a PR can be attached. I'll work on this when I can.

**Comment by pops106** [comment]
I have just updated to v1.1.1 after seeing the hismap_id fix and receiving this error.

Logger: homeassistant.setup
Source: custom_components/weback_vacuum/VacDevice.py:40
Integration: WeBack/Tesvor Vacuum ([documentation](https://github.com/Jezza34000/homeassistant_weback_component/blob/main/README.md), [issues](https://github.com/Jezza34000/homeassistant_weback_component/issues))
First occurred: 16:47:18 (1 occurrences)
Last logged: 16:47:18

Error during setup of component weback_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/weback_vacuum/__init__.py", line 90, in async_setup
    await vacuum_device.load_maps()
  File "/config/custom_components/weback_vacuum/VacDevice.py", line 40, in load_maps
    if not self.robot_status[self.ACTIVE_MAP_ID_PROP]:
KeyError: 'hismap_id'

**Comment by pauljrich1** [comment]
> 

I'm getting this error as well.

**Comment by talss89** [comment]
Thanks @pops106 and @pauljrich1. I've just made a fix, hoping to get a 1.1.2 release out soon.

Out of interest, what are your vacuum cleaner models? It would be good to start collecting some information on the differences between them.

**Comment by pauljrich1** [comment]
> Hi. I just push the release out 👍 Thank you @talss89

Thanks, this seems to have fixed the error!

**Comment by pops106** [comment]
> Thanks @pops106 and @pauljrich1. I've just made a fix, hoping to get a 1.1.2 release out soon.
> 
> Out of interest, what are your vacuum cleaner models? It would be good to start collecting some information on the differences between them.

1.1.2 has fixed the issue for me as well, much appreciated.

Mine is a old Ziglint D5 which doesn't seem to exist anymore but looking at the Tesvor manuals they are the same. So maybe buy out or rebrand not sure.

**Comment by talss89** [comment]
Great to hear @pops106. Thanks for the info. I've started collating model info on #14.

Seems like a lot of the hardware is actually manufactured by Yugong Shenzen originally, not sure if that's the case for yours too.
