### ISSUE TITLE
Spreading the word

### ISSUE THREAD

**Issue by pacjo** [Jezza34000/homeassistant_weback_component#16]
Hi,
I'm a long time user of https://github.com/opravdin/weback-unofficial, but it's no longer working. I found your integration today and it's awesome, but hard to find. I found by pure chance (while browsing github for anything to try to fix opravdin's work), so I can't imagine many people will find it too.

Would you mind making a post on Home Assistant community about it?
Also, will it be added to HACS repository?

**Comment by Jezza34000** [comment]
Hi !
Yes i will add it to HACS repo :-)

**Comment by Jezza34000** [comment]
Added to HACS default
Waiting for validation
https://github.com/hacs/default/pull/1791

**Comment by Jezza34000** [comment]
Done !
Weback is now HACS Default
