### ISSUE TITLE
Issue with Config

### ISSUE THREAD

**Issue by Kayinwonderland** [Jezza34000/homeassistant_weback_component#17]
Hey,

I did everything as you said. I run on the newest HA Version and put all the required info in the config.yaml. When I want to reload it, all I get is:

Invalid config for [weback_vacuum]: required key not provided @ data['weback_vacuum']['password']. Got None
required key not provided @ data['weback_vacuum']['region']. Got None
required key not provided @ data['weback_vacuum']['username']. Got None. (See ?, line ?).
Integration error: region - Integration 'region' not found.
Integration error: password - Integration 'password' not found.
Integration error: username - Integration 'username' not found.

**Comment by Jezza34000** [comment]
Hi,
Misconfigured "configuration.yaml" from your HomeAssistant.
You already close issue, it I think you found by yourself the solution 🙂

**Comment by Kayinwonderland** [comment]
Yes sorry it was my own mistake while copying I made a spacing issue 🙄🤦🏽‍♀️ now everything works great I loomed for something like this for years! Thanks ❤️
