### ISSUE TITLE
Error during setup of component weback_vacuum

### ISSUE THREAD

**Issue by fv71** [Jezza34000/homeassistant_weback_component#23]
Made an update from **1.1.2** to **1.1.3**.
The system encountered an installation error. Decided to remove version 1.1.2 and install clean 1.1.3, same result.
I am dropping the log:

> Home Assistant Core
> 2023-06-13 23:32:51.087 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration weback_vacuum which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-06-13 23:32:51.089 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration openweathermap_all which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-06-13 23:32:51.090 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-06-13 23:32:51.090 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-06-13 23:32:57.908 ERROR (MainThread) [homeassistant.components.hassio.handler] /store return code 500
> 2023-06-13 23:32:57.916 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store -
> 2023-06-13 23:33:06.194 INFO (MainThread) [custom_components.weback_vacuum] Creating new Weback Vacuum Robot component
> 2023-06-13 23:33:06.194 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi __init__
> 2023-06-13 23:33:06.194 DEBUG (MainThread) [custom_components.weback_vacuum] Weback vacuum robots: login started
> 2023-06-13 23:33:06.196 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi checking token validity : 2023-06-14 13:59:52.457199
> 2023-06-13 23:33:06.206 DEBUG (MainThread) [custom_components.weback_vacuum.webackapi] WebackApi token is valid
> 2023-06-13 23:33:06.206 ERROR (MainThread) [homeassistant.setup] Error during setup of component weback_vacuum
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
> result = await task
> ^^^^^^^^^^
> File "/config/custom_components/weback_vacuum/__init__.py", line 62, in async_setup
> log_res = await weback_api.login()
> ^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/weback_vacuum/webackapi.py", line 87, in login
> if self.verify_cached_creds():
> ^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/weback_vacuum/webackapi.py", line 136, in verify_cached_creds
> and self.user == creds_data["weback_token"]["user"]
> ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
> KeyError: 'user'
> 

Maybe this log will help to solve the problem. For now, I will leave this version with an error for a few days, and then I will roll back to 1.1.2 until this problem is solved.

Thanks for the help.

**Comment by fv71** [comment]
Logger: homeassistant.setup
Source: custom_components/weback_vacuum/webackapi.py:136
Integration: weback_vacuum (documentation, issues)
First occurred: 22:53:20 (1 occurrences)
Last logged: 22:53:20

Error during setup of component weback_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/weback_vacuum/__init__.py", line 62, in async_setup
    log_res = await weback_api.login()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weback_vacuum/webackapi.py", line 87, in login
    if self.verify_cached_creds():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weback_vacuum/webackapi.py", line 136, in verify_cached_creds
    and self.user == creds_data["weback_token"]["user"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'user'

**Comment by trnase** [comment]
having the same. wasn't sure what it was.
thought it was my update to the latest hassio version 2023.06.1
but didn't think i had the issue right after, untill i started re-organizing my config file.
don't want to return to previous version to check if it's not happening there, so let's see what will come out of it :)

**Comment by Jezza34000** [comment]
Fixed
https://github.com/Jezza34000/homeassistant_weback_component/releases/tag/1.1.4

**Comment by fv71** [comment]
> Fixed https://github.com/Jezza34000/homeassistant_weback_component/releases/tag/1.1.4

Yes, thanks for the quick fix. Everything works, although without a map (Abir X6)

**Comment by Jezza34000** [comment]
OK @fv71 if map problem persist open a new issue

**Comment by fv71** [comment]
Thanks **@Jezza34000** I do not know if anyone has a positive experience of working with the map on ABIR X6, what to understand or open a new problem, I know there have been attempts in this direction, but the result is unknown.

**Comment by Jezza34000** [comment]
Don't have any idea.
Try to open an issue with all information and we will ask @talss89 who develop this feature

**Comment by fv71** [comment]
Okay, I'll try to do that later. Thanks for the help.

**Comment by trnase** [comment]
thanks for the quick fix, saw the update, and after it worked again.
was thinkin it was me, but goog to see the result that fast
keep up the good work :D!
