### ISSUE TITLE
Firmware Update and Migration Procedures - Collaborative Effort

### ISSUE THREAD

**Issue by Jezza34000** [Jezza34000/homeassistant_weback_component#25]
As we navigate the changes resulting from the discontinuation of the WeBack service, we are aware that many of you may be seeking alternative solutions to ensure the continued functionality of your robot vacuum cleaners. In light of this, i would like to initiate a collaborative effort to gather information regarding firmware updates and migration procedures provided by manufacturers.

I kindly request that you contribute to this thread by sharing any details you have obtained from your robot's manufacturer regarding firmware updates and the process of transitioning to different platforms. Your valuable insights and experiences will greatly assist other users facing similar challenges.

Please provide the following information in your posts:

    Robot Model: [Specify the robot model for which you obtained the information]
    Manufacturer: [Name of the manufacturer]
    Firmware Update: [Details of the firmware update process, if available]
    Migration Procedure: [Information on how to migrate to a new platform, if provided]

By compiling and consolidating this information, i can create a comprehensive resource within our Home Assistant community, facilitating the transition away from the WeBack service.

I greatly appreciate your contributions and willingness to help fellow users during this transitional phase. Together, we can ensure a smoother experience and the continued functionality of our beloved robot vacuum cleaners.

Thank you for your support and participation.

**Comment by secureitall** [comment]
Robot Model:  EXVAC890 Glory
Manufacturer: Mamibot
Firmware Update: done via app
Migration Procedure:Upgrade https://www.mamibot.com/how-to-upgrade-weback-to-tuya-for-mamibot

**Comment by Jezza34000** [comment]
Robot Model: X600 / X600 PRO
Manufacturer: Neatsvor 
Firmware Update: Upgrade via direct WIFI connection on robot
Migration Procedure: Check at the video in the link
Link : https://drive.google.com/drive/folders/1wvupWHOstzPTKQ5xIV5krlzNCZzV-azN?spm=a2g0s.imconversation.0.0.1bc53e5f786OtY&usp=share_link

**Comment by Jezza34000** [comment]
Robot Model: S6 / S6 Turbo
Manufacturer: Tesvor
Firmware Update: 
- S6 : https://drive.google.com/file/d/170NBQZr0OWSeSukGjUhCUWgS2gNGF_9P/view?usp=sharing
- S6 Trubo : https://drive.google.com/file/d/12kfwS3WZzlvG17VYGzdmfenlVE8N2u-z/view?usp=sharing
Migration Procedure: https://www.tesvor.com/us/blog/post/how-to-upgrade-your-tesvor-s6-s6-turbo-from-weback-to-new-tesvor-app-by-yourself

**Comment by antonio1475** [comment]
> Robot Model: S6 / S6 Turbo Manufacturer: Tesvor Firmware Update:
> 
> * S6 : https://drive.google.com/file/d/170NBQZr0OWSeSukGjUhCUWgS2gNGF_9P/view?usp=sharing
> * S6 Trubo : https://drive.google.com/file/d/12kfwS3WZzlvG17VYGzdmfenlVE8N2u-z/view?usp=sharing
> 
> Migration Procedure: https://www.tesvor.com/us/blog/post/how-to-upgrade-your-tesvor-s6-s6-turbo-from-weback-to-new-tesvor-app-by-yourself

The migration procedure page no longer exists. Is there anything crucial other than reset and use the new app?

Can it still be used with HA today (with the new app)? I'm considering buying an S6 Turbo, only if it works with HA.

Thanks and sorry for the slight off-topic

**Comment by csnoke23** [comment]
> The migration procedure page no longer exists. Is there anything crucial other than reset and use the new app?
> 
> Can it still be used with HA today (with the new app)? I'm considering buying an S6 Turbo, only if it works with HA.
> 
> Thanks and sorry for the slight off-topic

You can still access the procedure page with the Wayback Machine:
http://web.archive.org/web/20230603154117/https://www.tesvor.com/us/blog/post/how-to-upgrade-your-tesvor-s6-s6-turbo-from-weback-to-new-tesvor-app-by-yourself

However, the process ended with a fatal error for my S6, which really changed nothing since it no longer worked with the apps anyway. Regardless, it still works with the remote and it's a good vacuum for pet owners. But, since it appears upgrading firmware was once supported by Tesvor before they changed their minds and purged the internet of instructions and files, I gather that the older models are wholly unsupported by the manufacturer and that I should be looking at other brands that don't bail on the customers.

**Comment by OlafKocanda** [comment]
I had my weback X500 running for 3 years now. Now I am able to connect it to Wi-Fi with the Weback app but not the Tesvor app. Since this morning it seems to not work anymore with the app: „offline unable to operate“

Robot Model: Tesvor X500
Manufacturer: weback
Firmware Update: ???
Migration Procedure:???

Sorry I do not know what to put at firmware update or migration procedure.

**Comment by Mendeln00** [comment]
Robot Model: x500
Manufacturer: Tesvor
Firmware Update: not available
Migration Procedure: `Dear Customer,
 
According to the QR code, in my opinion, your device can only connect to the Weback app and is not compatible with the Tesvor app. 
The attached QR codes are the ones we just tested. Please follow the method below to connect the Weback app.
1. Use the Weback app to scan the QR code we provide.
2. Select a 2.4G network and enter the correct password.
3. Press and hold the device's power button for 3-5 seconds and release it when you hear the beep.
4. Bring the phone close to the device and wait for it to connect.
Please note: You will need to scan the QR code I provided with the Weback app, not the QR code on the bottom of your device.
I hope this can help you.
Best regards,
Tesvor support team`

This is Tesvor's official answer to the question of why the robot vacuum cleaner is shown as offline in the Weback app. As it stands, there are no plans to migrate the X500.

**Comment by OlafKocanda** [comment]
> 4. ... Please note: You will need to scan the QR code I provided with the Weback app, not the QR code on the bottom of your device.

Can you share the QR code so I will give it another try?

> This is Tesvor's official answer to the question of why the robot vacuum cleaner is shown as offline in the Weback app. As it stands, there are no plans to migrate the X500.

Does this mean the robot is useless?

**Comment by amaenli** [comment]
Info:
If you create a new Account in WeBack, located with "China" as region, it's possible to add robots and interact with them through the WeBack-App. Worked for me. Don't know how long this workaround will last...

Hope this helps a few people out there.

**Comment by dulek** [comment]
Hi,

@Jezza34000, can we take one step back here? Where had you got information about discontinuation of the WeBack service? My robot info is below, but it _kinda works_. I was able to remove it and register it again yesterday. The region is 48, eu-central-1 in my case. What doesn't work is maps and all map-related functionality even in WeBack app.

I reached the vendor and their answer was that they know nothing about scaling down of WeBack app and assured me they'll pass complaint about maps not being available.

Thanks,
Michał

```
Robot Model: X-Style 
Manufacturer: RobotJet
Firmware Update: None
Migration Procedure: None
```

**Comment by Jezza34000** [comment]
Hi @dulek,

This information comes from my robot builder Neastvor, following a loss of my account, it turned out that the WeBack's servers no longer accepted new registrants. The manufacturer then replied to me that WeBack is going to close and that it was now offering the conversion of the platform to Tuya. 
By doing some more search my manufacturer was not the only one to take this step. 

May be be a last minute change?
I will update this project

**Comment by marine1988** [comment]
Robot Model: IKOHS
Manufacturer: Netbot S15
Firmware Update: None
Migration Procedure: None

**Comment by Jezza34000** [comment]
I am closing this issue, it seems that WeBack has changed its mind regarding this closure. New registrations are possible again.
