### ISSUE TITLE
[Request] Support For Tesvor S5 MAX using tesvor home app

### ISSUE THREAD

**Issue by Netesfiu** [Jezza34000/homeassistant_weback_component#29]
### Device brand

Tesvor

### Device model

S5 MAX

### Smartphone application

Tesvor home

### Component version

Tesvor Home app: 1.1.3 Tesvor vacuum: 6.7.9

### Describe the problem

I've recently bought a tesvor S5 MAX thinking that is could make it work with this application. The device can only be paired through the 'Tesvor Home' application, Weback, Tesvor, etc. does not work.

### Home Assistant Logs

N/A

**Comment by Jezza34000** [comment]
Hi @Netesfiu 
This means that your robot uses the Tuya/SmartLife's platform which is incompatible with the WeBack API and therefore this integration. In your case you must use Tuya to control your robot under HA.
