### ISSUE TITLE
Not connecting with Tesvor App

### ISSUE THREAD

**Issue by wilwizard1979** [Jezza34000/homeassistant_weback_component#3]
Hi, The integration is installed with HACS. It was missing 1 step in the instructions which I contributed and corrected in the read.me. I tried to set the application: to Tesvor as you can see below.

```
weback_vacuum:
  username: "XXX@gmail.com"
  password: "XXX"
  region: 49
  application: "Tesvor"
  #client_id: <api client, optionnal>
  #api_version: <api version used, optionnal> 
  #language : <language code 2 chars, optionnal>
```
I checked the log later and it was mentioned that the application name was wrong. I tried to remove uppercase and re-started having "tesvor" in the application. I got the same message when checking the log.
Then I decided to remove this line and re-started. Now I get the following message in the log:

```
2022-11-24 09:52:42.344 ERROR (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi login failed, wrong password
2022-11-24 09:52:42.345 ERROR (MainThread) [custom_components.weback_vacuum] Weback component was unable to login. Failed to setup
2022-11-24 09:52:42.345 INFO (MainThread) [homeassistant.setup] Setup of domain weback_vacuum took 11.6 seconds
2022-11-24 09:52:42.345 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration weback_vacuum: Integration failed to initialize.
```

I assume the integration is trying to log into the weback platform and not Tesvor.
What should I put in application to ensure that the log will be done in the Tesvor app?

**Comment by wilwizard1979** [comment]
Hi Jezza,

I did that, but still getting this:
```
2022-11-24 17:33:46.536 ERROR (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi login failed, application is not recognized, try to change 'application' field (this field is case sensitive) in your configuration.yaml
2022-11-24 17:33:46.538 ERROR (MainThread) [custom_components.weback_vacuum] Weback component was unable to login. Failed to setup
2022-11-24 17:33:46.539 INFO (MainThread) [homeassistant.setup] Setup of domain weback_vacuum took 7.1 seconds
2022-11-24 17:33:46.542 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration weback_vacuum: Integration failed to initialize.
2022-11-24 17:33:46.548 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; message=The following integrations and platforms could not be set up:

 - [weback_vacuum](https://github.com/Jezza34000/homeassistant_weback_component/blob/main/README.md) ([Show logs](/config/logs?filter=weback_vacuum))

Please check your config and [logs](/config/logs)., title=Invalid config, friendly_name=Invalid config @ 2022-11-24T17:33:46.548418+01:00>>
```

The same happens when I use `Tesvor` or `tesvor` in the application.

Thanks!

**Comment by Jezza34000** [comment]
Hi!
You close issue that mean you got solution?

**Comment by wilwizard1979** [comment]
Hi, I’ll post again. Maybe clicked by accident.

**Comment by Jezza34000** [comment]
OK the problem is here :

```
2022-11-24 17:33:46.536 ERROR (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi login failed, application is not recognized, try to change 'application' field (this field is case sensitive) in your configuration.yaml
```
Try with removing section application like this :

```
weback_vacuum:
  username: XXX@gmail.com
  password: XXX
  region: 49
```

And let me know if it's ok ?

**Comment by wilwizard1979** [comment]
Hi Jezza,

I tried what you suggested. Now I receive the following from the log:

```
2022-11-25 11:35:56.272 WARNING (MainThread) [homeassistant.setup] Setup of weback_vacuum is taking over 10 seconds.
2022-11-25 11:35:56.327 ERROR (MainThread) [custom_components.weback_vacuum.WebackApi] WebackApi login failed, wrong password
2022-11-25 11:35:56.329 ERROR (MainThread) [custom_components.weback_vacuum] Weback component was unable to login. Failed to setup
2022-11-25 11:35:56.335 INFO (MainThread) [homeassistant.setup] Setup of domain weback_vacuum took 15.1 seconds
2022-11-25 11:35:56.335 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration weback_vacuum: Integration failed to initialize.
2022-11-25 11:35:56.336 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; message=The following integrations and platforms could not be set up:

 - [weback_vacuum](https://github.com/Jezza34000/homeassistant_weback_component/blob/main/README.md) ([Show logs](/config/logs?filter=weback_vacuum))

Please check your config and [logs](/config/logs)., title=Invalid config, friendly_name=Invalid config @ 2022-11-25T11:35:56.336431+01:00>>
```

The entry in the Configuration.yaml looks like this now:

```
weback_vacuum:
  username: XXXX@gmail.com
  password: XXXX
  region: 49
  #application: Tesvor
  #client_id: <api client, optionnal>
  #api_version: <api version used, optionnal> 
  #language : <language code 2 chars, optionnal>
```

I´m of course using the correct user and password (as I do in the app).

I suspect that the integration is still trying to connect to WeBack. I couldn´t find in the code any switch to the Tesvor App. All API references seem to be connected to WeBack and not Tesvor.

**Comment by Jezza34000** [comment]
OK that mean application field is required. 
My problem is : i don't know what is expected by server when you're using Tesvor app... 
I found an other github's user who made a plugin for homebridge and Tesvor vacuum.
Maybe he could help us, about what server are expecting... i send him a message...

**Comment by wilwizard1979** [comment]
Thanks. I tried some obvious variants like:
`TesvorApp` `Tesvorapp` `tesvorapp` `TesvorApi` `tesvorapi`
But it is all guess. I will stop with that.

It might worth to say that I´m using the weback_robot_vacuum integration, for a Tesvor Robot x500 which is working perfectly.
Link in Github: [https://github.com/agustin-e/weback-home-assistant-component](url)
The problem lays now with my Tesvor M1 using Tesvor App.

I still believe that the integration is suitable only for WebackApi. I read the code and I don´t see any reference to another platform like Tesvor. I can also raise a question to the support of Tesvor, but I´m not sure if they can help.

I will be attentive to your reply and I can contribute to do any necessary test to validate this integration now to Tesvor. This is by the way informed to be the only compatible platform for the new Tesvor Robots.

**Comment by Jezza34000** [comment]
OK,
I'm not sure to understand everything...
You are using 2 robots ? 
-Tesvor Robot x500
-Tesvor M1
This 2 robots are using WeBack app or Tesvor app ? And which one are working or not ?
About this component : [https://github.com/agustin-e/weback-home-assistant-component](https://github.com/agustin-e/weback-home-assistant-component)
This author use inspiration from my original code from Jeedom's plugin (same as HomeAssistant) [https://github.com/Jezza34000/weback](https://github.com/Jezza34000/weback) but i identify a lot of flaw in his code, causing heavy charge in WSS link. it's now abandonned he don't answer to any issues neither on HA community WeBack thread...

**Comment by wilwizard1979** [comment]
Thanks Jezza for explaining to me.
So, to clarify. I live in a multi floor house, so I decided to have 1 Robot in each floor. Currently I have:
- A Tesvor Robot x500 that I bought 2 years ago, added to WeBack App and using the code from Agustin-e
- A Tesvor Robot M1 that I bought a few days ago, added to Tesvor App and using your code

I would be happy to use just your code, but I still don´t understand if it will be possible to have 2 Robot entities in the same integration, specially if they are connected to different applications (WeBack and Tesvor). So I decided to resolve one problem at a time. For the moment I will keep the integration that is working while attempting yours to work using the Tesvor App.

I hope this clarifies.

**Comment by Jezza34000** [comment]
OK, well...
I think the Tesvor M1 is not using the WeBack platform at all.
I got exactly the same problem, i explain : 
i have 2 robots -Neatsvor X600 -Neatsvor X600 PRO (same robot, but different battery, and 1 more vacuum speed)
But with my integration, i can control only the Neatsvor X600, the X600 PRO is not WeBack compatible... (it use SmartLife/Tuya plateform)
i take a look at the new Tesvor app and it look pretty close to my SmartLife app i use for Neatsvor X600 PRO.
I'm pretty it use SmartLife/Tuya plateform now.
You could try one thing : Download SmartLife or Tuya, and try to connect with your Tesvor credentials if it work that mean it using SmartLife/Tuya platform :-)

**Comment by wilwizard1979** [comment]
Hi Jezza,

Thanks for the very good hint. I could add it to Tuya and since I had already Tuya integration in HA it was immediately recognized as a new Device.
It is very likely that your products are exactly the same ones and perhaps just rebranded. I purchased M1 for the same reason of being more powerful (4000Pa). I could not find all speed selectors in the Integration, but I think I will survive.

William Vidal

**Comment by Jezza34000** [comment]
Ok perfect then :
-Tesvor x500 use WeBack platform and could be use with this integration
-Tesvor M1 use Smart life/Tuyau platform and couldn't be used with this integration.

And I notice same problem, it's not possible to set MAX vacuum speed.
In my case I fixed it to MAX speed, vacuum is always running while I'm away from home. It's just annoying for the cat who try to sleep 😂

**Comment by wilwizard1979** [comment]
Thanks Jezza, I think we have the same devices in the end! :-D
It would be great if we could add the speed options in Tuya app and also the battery status. But this would be a subject of another forum.
If you are interested to investigate this together, please let me know.
I think for me we can close this issue, but I would also recommend that you add in your description that Tesvor App seems to not be supported by this integration.
I suggested also a step in your installation which is to copy the folder to the "custom_components". Not sure if you received my suggestion?
Again, if you are interested to further explore on Tuya and see if we can add more status, I´m help to create a joint work here.

**Comment by Jezza34000** [comment]
hi !
i just updated my integration description and removing information about Tesvor support. I add a warning section to explain that platform specification (smartife/tuya vs weback)
Yes i would like t invest and make a PR for tuya to improve thoses missing params, but i have so many idea to code and not engouh hours in a day :-)
About this setp to copy folder i don't really understand ? With HACS installation it's really more easy to done it ? 
Thank you for your precious help about that Tesvor app :-)

**Comment by wilwizard1979** [comment]
Hi Jezza, no problem, my pleasure.
Regarding the Copy Folder in Home Assistant, I meant that someone needs to copy the content of your `custom_components` folder to the `config/custom_components` of Home Assistant. If this is not done, the call to `weback_vacuum:` is not recognized.

Regarding the coding, I would be happy to learn and help. I just don´t know how to start. My time is of course very limited.
I used to code a lot in the past using Pascal, VBA and Delphi. I was also a programming teacher. Later at work I used to connect industrial devices to automation systems using different languages like Modbus, Profibus or specific protocol (called Alien Protocols at that time). I had to go to ASCII level sometimes. My skills to Program are quite good. With the new languages I just feel a bit rusty, :-D. But I also see so much room for improvement with just a few minutes exploring. 
Let me know if we can do something together and how we could also Exchange messages and information.

**Comment by Jezza34000** [comment]
Ok i will add a section "manual installation".
If you know Pascal & Delphi it will be pretty much easy to learn Python. But my advice : do not start learning Python with Home Assistant. HA's architecture is a bit difficult to understand at first.

**Comment by Jezza34000** [comment]
Hi !
One more things ! Could you try this integrations with your Tesvor X500 ?
It seems an other user experiencing issues and it has never worked ?
[https://github.com/Jezza34000/homeassistant_weback_component/issues/5](https://github.com/Jezza34000/homeassistant_weback_component/issues/5)

And reply directly on the issues :+1:
