### ISSUE TITLE
Does this work locally or require their servers?

### ISSUE THREAD

**Issue by Keavon** [Jezza34000/homeassistant_weback_component#7]
It would be nice if I could do the setup just once then block the vacuum from connecting to the Internet on my router. Could you please clarify if this all works locally once it's set up, or if it just makes calls over the Internet and back to the device? Thanks.

**Comment by Jezza34000** [comment]
Hi !
Definitively not.
This app is cloud only. 
Using thoses vacuum robot locally without cloud, require a hudge work to disassemble their internal firmware.
